In [50]:
import pandas as pd
from math import isnan

In [51]:
# variable = 'expression_density'
variable = 'expression_energy'

In [52]:
info_df = pd.read_csv('data/info.csv')
info_df

,receptor,experiment_id,plane,parent_area_id,filename,has_data
0,Drd1,71307280.0,2.0,669,gene_Drd1_exp_71307280_target_area_id_778.csv,True
1,Drd1,352.0,1.0,669,gene_Drd1_exp_352_target_area_id_778.csv,True
2,Drd1,353.0,2.0,669,gene_Drd1_exp_353_target_area_id_778.csv,True
3,Drd1,354.0,2.0,669,gene_Drd1_exp_354_target_area_id_778.csv,True
4,Drd2,358.0,2.0,669,gene_Drd2_exp_358_target_area_id_778.csv,True
...,...,...,...,...,...,...
131,Hrh2,74724750.0,1.0,669,gene_Hrh2_exp_74724750_target_area_id_778.csv,True
132,Hrh2,69257761.0,2.0,669,gene_Hrh2_exp_69257761_target_area_id_778.csv,True
133,Hrh3,71393412.0,2.0,669,gene_Hrh3_exp_71393412_target_area_id_778.csv,True
134,Hrh3,73636034.0,1.0,669,gene_Hrh3_exp_73636034_target_area_id_778.csv,True
135,Hrh4,69257767.0,2.0,669,gene_Hrh4_exp_69257767_target_area_id_778.csv,True

plane_of_section_id = 1 for coronal

plane_of_section_id = 2 for saggital

In [53]:
sheet1_df = []
for receptor in info_df['receptor'].unique():
    exp_density_average = 0
    exps = 0
    for exp_id in info_df[(info_df['receptor']==receptor) & (info_df['has_data']==True)]['experiment_id']:
        exp_df = pd.read_csv('data/'+info_df[(info_df['receptor']==receptor) & (info_df['experiment_id']==exp_id)]['filename'].item())
        exp_density_average += exp_df[variable].item()
        exps+=1
    if exps==0:
        sheet1_df.append({'receptor': receptor,variable+'_average': 'N/A'})
        continue
    else: sheet1_df.append({'receptor': receptor,variable+'_average': exp_density_average / exps})
sheet1_df = pd.DataFrame(sheet1_df)
sheet1_df

    receptor expression_energy_average
0       Drd1                  0.330035
1       Drd2                  0.123916
2       Drd3                  0.112358
3       Drd4                  0.502085
4       Drd5                  0.020835
5      Htr1a                  1.729595
6      Htr1b                  0.123792
7      Htr1d                  0.250043
8      Htr1e                       N/A
9      Htr1f                   10.3105
10     Htr2a                     3.535
11     Htr2b                  0.050204
12     Htr2c                  0.158495
13      Htr4                  0.105793
14     Htr5a                  0.144509
15    Htr5bp                       N/A
16      Htr6                  0.091265
17      Htr7                  0.018475
18     Htr3a                  0.440207
19     Htr3b                  0.088291
20     Htr3c                       N/A
21     Htr3d                       N/A
22     Htr3e                       N/A
23    Chrna1                  7.049169
24    Chrna2                  2.870545
25    Chrna3                  0.072657
26    Chrna4                  2.034627
27    Chrna5                  0.168498
28    Chrna6                  0.573525
29    Chrna7                  1.092547
30    Chrna8                       N/A
31   Chrna9                        N/A
32  Chrna10                        N/A
33    Chrnb1                  0.132565
34    Chrnb2                  2.203159
35    Chrnb3                  0.273054
36    Chrnb4                       N/A
37     Chrnd                  3.545716
38     Chrne                     0.114
39     Chrng                  0.423137
40     Chrm1                  22.30815
41     Chrm2                  6.251235
42     Chrm3                  7.388948
43     Chrm4                 13.612785
44     Ch4m5                       N/A
45      Cnr1                   7.46451
46      Cnr2                  0.228905
47     Oprd1                  1.766715
48     Oprk1                  0.115637
49     Oprl1                   2.53416
50     Oprm1                   0.10002
51      Hrh1                  2.014163
52      Hrh2                  0.942742
53      Hrh3                   3.15745
54      Hrh4                  0.085461

In [54]:
plane_dict = {1: 'coronal', 2: 'saggital'}

sheet2_df = []
for receptor in info_df['receptor'].unique():
#     exp_density_average = 0
#     exps = 0
    if info_df[info_df['receptor']==receptor]['experiment_id'].isnull().values.any():
        sheet2_df.append({'receptor': receptor,'experiment_id': 'N/A','plane': 'N/A',variable: 'N/A'})
        continue
    for exp_id in info_df[info_df['receptor']==receptor]['experiment_id']:
        exp_df = info_df[(info_df['receptor']==receptor) & (info_df['experiment_id']==exp_id)]
        if exp_df['has_data'].item() == False:
            sheet2_df.append({'receptor': receptor,'experiment_id': exp_id,'plane': plane_dict[int(exp_df['plane'].item())],variable: 'N/A'})
            continue
        union_data_df = pd.read_csv('data/'+exp_df['filename'].item())
        exp_density = union_data_df[variable].item()
        sheet2_df.append({'receptor': receptor,'experiment_id': exp_id,'plane': plane_dict[int(exp_df['plane'].item())],variable: exp_density})
#     if exps==0:
#         sheet2_df.append({'receptor': receptor,'expression_density_average': 'N/A'})
#         continue
#     else: sheet2_df.append({'receptor': receptor,'experiment_id': 0,'plane': 'coronal','expression_density': exp_density_average})
sheet2_df = pd.DataFrame(sheet2_df)
sheet2_df

    receptor experiment_id     plane expression_energy
0       Drd1    71307280.0  saggital          0.624731
1       Drd1         352.0   coronal          0.590057
2       Drd1         353.0  saggital          0.105353
3       Drd1         354.0  saggital               0.0
4       Drd2         358.0  saggital          0.185884
..       ...           ...       ...               ...
131     Hrh2    74724750.0   coronal          0.355975
132     Hrh2    69257761.0  saggital           1.52951
133     Hrh3    71393412.0  saggital           3.89164
134     Hrh3    73636034.0   coronal           2.42326
135     Hrh4    69257767.0  saggital          0.085461

[136 rows x 4 columns]

In [55]:
with pd.ExcelWriter(variable+'_data.xlsx') as writer:  
    sheet1_df.to_excel(writer, sheet_name='average_'+variable)
    sheet2_df.to_excel(writer, sheet_name='experiment_'+variable)