In [101]:
import pandas as pd
from math import isnan

In [102]:
# variable = 'expression_density'
variable = 'expression_energy'
structures = {
    'VISam5': 433,
    'VISpm5': 565,
    'RSPagl': 894,
    'VISp5': 778
}

In [103]:
# info_df1 = pd.read_csv('V2m_layer_5_data/info.csv')
# info_df2 = pd.read_csv('VISp5_data/info.csv')
# info_df1.head()
info_df = pd.read_csv('data/info.csv')
info_df

,receptor,experiment_id,plane,query_area_id,filename,has_data
0,Drd1,71307280.0,2.0,"[433, 565, 894, 778]","gene_Drd1_exp_71307280_query_area_id_[433, 565...",True
1,Drd1,352.0,1.0,"[433, 565, 894, 778]","gene_Drd1_exp_352_query_area_id_[433, 565, 894...",True
2,Drd1,353.0,2.0,"[433, 565, 894, 778]","gene_Drd1_exp_353_query_area_id_[433, 565, 894...",True
3,Drd1,354.0,2.0,"[433, 565, 894, 778]","gene_Drd1_exp_354_query_area_id_[433, 565, 894...",True
4,Drd2,358.0,2.0,"[433, 565, 894, 778]","gene_Drd2_exp_358_query_area_id_[433, 565, 894...",True
...,...,...,...,...,...,...
134,P2rx6,75551463.0,1.0,"[433, 565, 894, 778]","gene_P2rx6_exp_75551463_query_area_id_[433, 56...",True
135,P2rx6,72183007.0,2.0,"[433, 565, 894, 778]","gene_P2rx6_exp_72183007_query_area_id_[433, 56...",True
136,P2rx7,75551477.0,1.0,"[433, 565, 894, 778]","gene_P2rx7_exp_75551477_query_area_id_[433, 56...",True
137,P2rx7,71280580.0,2.0,"[433, 565, 894, 778]","gene_P2rx7_exp_71280580_query_area_id_[433, 56...",True
138,P2rx7,81600560.0,2.0,"[433, 565, 894, 778]","gene_P2rx7_exp_81600560_query_area_id_[433, 56...",True

In [104]:
info_df['experiment_id'].unique()

array([7.13072800e+07, 3.52000000e+02, 3.53000000e+02, 3.54000000e+02,
       3.58000000e+02, 3.57000000e+02, 8.17907280e+07, 3.59000000e+02,
       1.00142530e+08, 7.50384310e+07, 1.12650336e+08, 8.17907100e+07,
       7.95566160e+07, 7.93943550e+07, 5.84000000e+02, 5.83000000e+02,
       7.99133180e+07, 7.13934180e+07,            nan, 6.98598670e+07,
       8.16713440e+07, 7.95567080e+07, 7.16641300e+07, 7.36360980e+07,
       7.13934240e+07, 7.21196580e+07, 6.92578490e+07, 7.13934300e+07,
       6.92579810e+07, 7.13934360e+07, 7.05931420e+07, 7.47247600e+07,
       6.87454080e+07, 7.46413180e+07, 7.55514650e+07, 1.00146096e+08,
       7.55514600e+07, 7.55514800e+07, 7.21196550e+07, 6.97347230e+07,
       1.17400000e+03, 1.17300000e+03, 7.74547220e+07, 7.58265670e+07,
       7.48216010e+07, 7.55514810e+07, 7.55514610e+07, 7.56512130e+07,
       6.92371070e+07, 7.45117380e+07, 7.58311740e+07, 7.58887520e+07,
       7.76203870e+07, 2.09700000e+03, 8.17907240e+07, 8.16713420e+07,
       2.09800000e+03, 7.97604700e+07, 7.04367470e+07, 7.49886800e+07,
       7.05931330e+07, 7.46348190e+07, 7.58887380e+07, 7.55514660e+07,
       7.05931340e+07, 7.97621140e+07, 7.39074970e+07, 6.92370830e+07,
       7.05603430e+07, 7.99125560e+07, 7.74648620e+07, 2.09500000e+03,
       2.09600000e+03, 7.99132780e+07, 7.95916410e+07, 2.61000000e+02,
       2.63000000e+02, 2.62000000e+02, 2.82000000e+02, 2.83000000e+02,
       7.99134470e+07, 2.84000000e+02, 7.95916750e+07, 2.11200000e+03,
       2.11100000e+03, 1.00144385e+08, 1.12646675e+08, 8.05172170e+07,
       1.00145378e+08, 6.98371910e+07, 7.50772320e+07, 6.98608400e+07,
       8.03422340e+07, 7.99125720e+07, 6.92577550e+07, 7.22837920e+07,
       7.47247500e+07, 6.92577610e+07, 7.13934120e+07, 7.36360340e+07,
       6.92577670e+07, 8.16001200e+07, 6.98632460e+07, 7.51446930e+07,
       7.56944280e+07, 6.92582860e+07, 1.00144178e+08, 1.80000000e+03,
       1.12203915e+08, 1.90700000e+03, 6.92582800e+07, 1.00144167e+08,
       7.61357480e+07, 7.58898270e+07, 7.58908350e+07, 6.98609860e+07,
       7.55514730e+07, 7.58311760e+07, 7.58887510e+07, 7.38344630e+07,
       6.98609870e+07, 7.55514740e+07, 6.98632450e+07, 7.55514750e+07,
       7.55514630e+07, 7.21830070e+07, 7.55514770e+07, 7.12805800e+07,
       8.16005600e+07])

plane_of_section_id = 1 for coronal

plane_of_section_id = 2 for saggital

In [105]:
plane_dict = {1: 'coronal', 2: 'saggital'}

data_df = []
for receptor in info_df['receptor'].unique():
    for exp_id in info_df[info_df['receptor']==receptor]['experiment_id']:
        exp_df = info_df[(info_df['receptor']==receptor) & (info_df['experiment_id']==exp_id)]
        if isnan(exp_id):
            data_df.append({'receptor': receptor,'experiment_id': 'N/A','plane': 'N/A','structure': 'N/A','structure_id': 'N/A',variable: 'N/A'})
        elif exp_df['has_data'].item()==False:
            data_df.append({'receptor': receptor,'experiment_id': int(exp_id),'plane': plane_dict[int(exp_df['plane'].item())],
                            'structure': 'N/A','structure_id': 'N/A',variable: 'N/A'})
        else:
            for s in structures.keys():
                union_data_df = pd.read_csv('data/'+exp_df['filename'].item())
                exp_var_df = union_data_df[union_data_df['structure_id']==structures[s]][variable]
                if len(exp_var_df)==0: exp_variable = 'N/A'
                else: exp_variable = exp_var_df.item()
                data_df.append({'receptor': receptor,'experiment_id': int(exp_id),'plane': plane_dict[int(exp_df['plane'].item())],
                        'structure': s,'structure_id': structures[s],variable: exp_variable})
        
sheet3_df = pd.DataFrame(data_df)
sheet3_df

    receptor experiment_id     plane structure structure_id expression_energy
0       Drd1      71307280  saggital    VISam5          433          0.686973
1       Drd1      71307280  saggital    VISpm5          565          0.753131
2       Drd1      71307280  saggital    RSPagl          894            0.8847
3       Drd1      71307280  saggital     VISp5          778          0.624731
4       Drd1           352   coronal    VISam5          433          0.521178
..       ...           ...       ...       ...          ...               ...
512    P2rx7      71280580  saggital     VISp5          778           0.12853
513    P2rx7      81600560  saggital    VISam5          433          0.701404
514    P2rx7      81600560  saggital    VISpm5          565          0.472398
515    P2rx7      81600560  saggital    RSPagl          894          0.274834
516    P2rx7      81600560  saggital     VISp5          778           1.06944

[517 rows x 6 columns]

In [106]:
df = pd.read_excel("C:\\Users\\sarfi\\Desktop\\Drive\\KR1\\list_of_receptors.xlsx")
receptors = [x.lower()[0].upper()+x.lower()[1:] for x in list(df['Receptor'])]

In [107]:
sheet2_df = []
for R in receptors:
    for S in structures:
        df = sheet3_df[(sheet3_df['receptor']==R) & (sheet3_df['structure']==S)]
        if len(df)==0:
            sheet2_df.append({'receptor': R,'structure': 'N/A','structure_id': 'N/A','average_'+variable: 'N/A'})
            continue
        exp_var = df[df[variable].apply(lambda x: isinstance(x, float))][variable].mean()
        sheet2_df.append({'receptor': R,'structure': S,'structure_id': structures[S],'average_'+variable: exp_var})
sheet2_df = pd.DataFrame(sheet2_df)
sheet2_df

    receptor structure structure_id average_expression_energy
0       Drd1    VISam5          433                  0.430799
1       Drd1    VISpm5          565                  0.550058
2       Drd1    RSPagl          894                  0.564233
3       Drd1     VISp5          778                  0.330035
4       Drd2    VISam5          433                  0.108665
..       ...       ...          ...                       ...
275    P2rx6     VISp5          778                  0.206762
276    P2rx7    VISam5          433                  0.394186
277    P2rx7    VISpm5          565                  0.235894
278    P2rx7    RSPagl          894                  0.171869
279    P2rx7     VISp5          778                   0.47379

[280 rows x 4 columns]

In [108]:
sheet2_df[(sheet2_df['receptor']=='Htr1e') & (sheet2_df['structure_id']!=778)]

   receptor structure structure_id average_expression_energy
32    Htr1e       N/A          N/A                       N/A
33    Htr1e       N/A          N/A                       N/A
34    Htr1e       N/A          N/A                       N/A
35    Htr1e       N/A          N/A                       N/A

In [109]:
sheet1_df = []
for R in receptors:
    v2m_df = sheet2_df[(sheet2_df['receptor']==R) & (sheet2_df['structure_id']!=778)]
    v1_df = sheet2_df[(sheet2_df['receptor']==R) & (sheet2_df['structure_id']==778)]
    if len(v2m_df[v2m_df['average_'+variable].apply(lambda x: isinstance(x, float))])==0: v2m_exp_var = 'N/A'
    else: v2m_exp_var = v2m_df['average_'+variable].mean()
    if len(v1_df[v1_df['average_'+variable].apply(lambda x: isinstance(x, float))])==0: v1_exp_var = 'N/A'
    else: v1_exp_var = v1_df['average_'+variable].item()
        
    sheet1_df.append({'receptor': R,'structure': 'V2m','average_'+variable: v2m_exp_var})
    sheet1_df.append({'receptor': R,'structure': 'VISp5','average_'+variable: v1_exp_var})
sheet1_df = pd.DataFrame(sheet1_df)
sheet1_df

    receptor structure average_expression_energy
0       Drd1       V2m                   0.51503
1       Drd1     VISp5                  0.330035
2       Drd2       V2m                   0.17597
3       Drd2     VISp5                  0.123916
4       Drd3       V2m                  0.349375
..       ...       ...                       ...
135    P2rx5     VISp5                  0.250756
136    P2rx6       V2m                  0.506544
137    P2rx6     VISp5                  0.206762
138    P2rx7       V2m                  0.267317
139    P2rx7     VISp5                   0.47379

[140 rows x 3 columns]

In [110]:
with pd.ExcelWriter(variable+'_data.xlsx') as writer:  
    sheet1_df.to_excel(writer, sheet_name='Averaged Structures')
    sheet2_df.to_excel(writer, sheet_name='Averaged Experiments')
    sheet3_df.to_excel(writer, sheet_name='Full Data')